from .resolvers_city import *
from .resolvers_country import *
from .resolvers_course import *
from .resolvers_faculty import *
from .resolvers_professor import *
from .resolvers_professor_course import *
from .resolvers_region import *
from .resolvers_science_domain import *
from .resolvers_specialization import *
from .resolvers_university import *
from .resolvers_user import *
from .resolvers_tag import *
from .resolver_review import *