from ariadne import (MutationType, QueryType, ObjectType)

from . import *  # imports all imports from __init__.py

query = QueryType()
mutation = MutationType()
country = ObjectType("Country")
region = ObjectType("Region")
city = ObjectType("City")
university = ObjectType("University")
faculty = ObjectType("Faculty")
specialization = ObjectType("Specialization")
science_domain = ObjectType("ScienceDomain")
course = ObjectType("Course")
professor_course = ObjectType("ProfessorCourse")
professor = ObjectType("Professor")
user = ObjectType("User")
tag = ObjectType("Tag")
review = ObjectType("Review")
teaches_details = ObjectType("TeachesDetails")

query.set_field("country", resolve_country)
region.set_field("country", resolve_country)
query.set_field("allCountries", resolve_all_countries)
mutation.set_field("createCountryByISO", resolve_create_country_by_ISO)
mutation.set_field("updateCountry", resolve_update_country)
mutation.set_field("deleteCountry", resolve_delete_country)

query.set_field("region", resolve_region)
city.set_field("region", resolve_region)
query.set_field("allRegions", resolve_all_regions)
mutation.set_field("createRegion", resolve_create_region)
mutation.set_field("updateRegion", resolve_update_region)
mutation.set_field("deleteRegion", resolve_delete_region)

query.set_field("city", resolve_city)
university.set_field("city", resolve_city)
query.set_field("allCities", resolve_all_cities)
region.set_field("cities", resolve_all_cities)
mutation.set_field("createCity", resolve_create_city)
mutation.set_field("updateCity", resolve_update_city)
mutation.set_field("deleteCity", resolve_delete_city)

query.set_field("university", resolve_university)
review.set_field("university", resolve_university)
faculty.set_field("university", resolve_university)
query.set_field("allUniversities", resolve_all_universities)
city.set_field("universities", resolve_all_universities)
mutation.set_field("createUniversity", resolve_create_university)
mutation.set_field("updateUniversity", resolve_update_university)
mutation.set_field("deleteUniversity", resolve_delete_university)

query.set_field("faculty", resolve_faculty)
review.set_field("faculty", resolve_faculty)
specialization.set_field("faculty", resolve_faculty)
query.set_field("allFaculties", resolve_all_faculties)
university.set_field("faculties", resolve_all_faculties)
mutation.set_field("createFaculty", resolve_create_faculty)
mutation.set_field("updateFaculty", resolve_update_faculty)
mutation.set_field("deleteFaculty", resolve_delete_faculty)

query.set_field("specialization", resolve_specialization)
review.set_field("specialization", resolve_specialization)
query.set_field("allSpecializations", resolve_all_specialization)
faculty.set_field("specializations", resolve_all_specialization)
course.set_field("specializations", resolve_all_specialization)
science_domain.set_field("specializations", resolve_all_specialization)
mutation.set_field("createSpecialization", resolve_create_specialization)
mutation.set_field("updateSpecialization", resolve_update_specialization)
mutation.set_field("deleteSpecialization", resolve_delete_specialization)

query.set_field("scienceDomain", resolve_science_domain)
query.set_field("allScienceDomains", resolve_all_science_domains)
mutation.set_field("createScienceDomain", resolve_create_science_domain)
mutation.set_field("updateScienceDomain", resolve_update_science_domain)
mutation.set_field("connectScienceDomainToSpecialization", resolve_connect_science_domain_to_specialization)
mutation.set_field("disconnectScienceDomainFromSpecialization", resolve_disconnect_science_domain_from_specialization)
mutation.set_field("deleteScienceDomain", resolve_delete_science_domain)

teaches_details.set_field("course", resolve_course)
query.set_field("course", resolve_course)
review.set_field("course", resolve_course)
query.set_field("allCourses", resolve_all_courses)
mutation.set_field("createCourse", resolve_create_course)
mutation.set_field("updateCourse", resolve_update_course)
mutation.set_field("deleteCourse", resolve_delete_course)

query.set_field("professor", resolve_professor)
query.set_field("allProfessors", resolve_all_professors)
professor_course.set_field("professor", resolve_professor)
mutation.set_field("createProfessor", resolve_create_professor)
mutation.set_field("updateProfessor", resolve_update_professor)
# mutation.set_field("connectProfessorToProfessorCourse", resolve_connect_professor_to_professor_course)
# mutation.set_field("reconnectProfessorToProfessorCourse", resolve_reconnect_professor_to_professor_course)
# mutation.set_field("disconnectProfessorFromProfessorCourse", resolve_disconnect_professor_from_professor_course)
mutation.set_field("deleteProfessor", resolve_delete_professor)
professor.set_field("teaches", resolve_professor_teaches)

query.set_field("user", resolve_user)
review.set_field("author", resolve_user)
query.set_field("allUsers", resolve_all_users)
specialization.set_field("users", resolve_all_users)
course.set_field("users", resolve_all_users)
mutation.set_field("createUser", resolve_create_user)
mutation.set_field("updateUser", resolve_update_user)
mutation.set_field("connectUserToSpecialization", resolve_connect_user_to_specialization)
mutation.set_field("disconnectUserFromSpecialization", resolve_disconnect_user_from_specialization)
mutation.set_field("connectUserToCourse", resolve_connect_user_to_course)
mutation.set_field("disconnectUserFromCourse", resolve_disconnect_user_from_course)
mutation.set_field("deleteUser", resolve_delete_user)

query.set_field("tag", resolve_create_tag)
query.set_field("allTags", resolve_all_tags)
mutation.set_field("createTag", resolve_create_tag)
mutation.set_field("updateTag", resolve_update_tag)
mutation.set_field("deleteTag", resolve_delete_tag)

query.set_field("review", resolve_review)
query.set_field("allReviews", resolve_all_reviews)
tag.set_field("reviews", resolve_all_reviews)
university.set_field("reviews", resolve_all_reviews)
faculty.set_field("reviews", resolve_all_reviews)
specialization.set_field("reviews", resolve_all_reviews)
course.set_field("reviews", resolve_all_reviews)
professor_course.set_field("reviews", resolve_all_reviews)
mutation.set_field("createReview", resolve_create_review)
mutation.set_field("updateReview", resolve_update_review)
mutation.set_field("deleteReview", resolve_delete_review)